### ISSUE TITLE
Point of this mod?

### ISSUE THREAD

**Issue by JustAlittleWolf** [ItzjustElias/FastMathMod#1]
Minecraft already uses a lookup table for fast sin and cos calculations.

**Comment by ItzjustElias** [comment]
This mod is still in early development and there will be updates in the future with better ways of improving the math in Minecraft. I did not know that Minecraft already uses a lookuptable. Where did you find this information?

**Comment by JustAlittleWolf** [comment]
> Where did you find this information?

You can look at the decompiled Minecraft source code, either by decompiling Minecraft with a proper decompiler (takes a while), or by using your IDE (IntelliJ does this) to look at the source for MathHelper.

Also here: https://maven.fabricmc.net/docs/yarn-1.21.2+build.1/net/minecraft/util/math/MathHelper.html
> Trigonometric functions defined in this class use the "sine table", a pre-calculated table of sin(N) (0 <= N < pi * 2).

**Comment by xboct02** [comment]
---- Minecraft Crash Report ----
// Shall we play a game?

Time: 2024-12-07 00:23:09
Description: Initializing game

java.lang.NoClassDefFoundError: org/apache/commons/math3/util/FastMath
	at org.elias.fastmath.MathUtil.initialize(MathUtil.java:16)
	at org.elias.fastmath.MathUtil.sinAndCos(MathUtil.java:23)
	at net.minecraft.class_3532.method_15362(class_3532.java:973)
	at net.minecraft.class_9975.method_62309(class_9975.java:105)
	at net.minecraft.class_9975.method_62311(class_9975.java:51)
	at net.minecraft.class_9975.<init>(class_9975.java:36)
	at net.minecraft.class_761.<init>(class_761.java:122)
	at net.minecraft.class_310.<init>(class_310.java:656)
	at net.minecraft.client.main.Main.main(Main.java:248)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:557)
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:84)
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:28)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.math3.util.FastMath
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.loadClassOnly(KnotClassDelegate.java:204)
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:176)
	at org.quiltmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:239)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	... 14 more

**Comment by ItzjustElias** [comment]
@xboct02 what minecraft version of fabric do you use?

**Comment by xboct02** [comment]
> Какую версию ткани Minecraft (в вашем случае лоскутное одеяло) вы используете? Может случиться так, что версии или зависимости не совпадают между квилтом и тканью.
> 
> Используете ли вы какие-либо другие моды в сочетании с модом Super Fast Math?

Main optimization mods, 1.21.3 QILT 0.27.1-beta.1

**Comment by xboct02** [comment]
abouObviously, there is no support/fast match library. Usually, mods add this functionality.

**Comment by ItzjustElias** [comment]
@xboct02 I'm currently working on a version for 1.21.4 QuiltMC. So there will be a fix shortly. :)

**Comment by xbxct** [comment]
> В настоящее время я работаю над версией для 1.21.4 QuiltMC. Так что в скором времени будет исправление. :)

The problem still exists on the new version

**Comment by ItzjustElias** [comment]
I know thats for fabric, not for quilt. Quilt version hasnt been released yet

**Comment by xbxct** [comment]
> Я знаю, что это для ткани, а не для лоскутного одеяла. Версия для лоскутного одеяла еще не выпущена

QILT supports fabrick mods. It would be more likely to see an incompatibility error when explicitly specifying supported versions, but the error simply points to a missing math library class. This library can be added to a mod instead of asking for a game.
